name: Build RPM

on: push

jobs:
  build-ol8:
    name: Build RPM on Oracle Linux 8
    runs-on: ubuntu-latest

    container:
      image: oraclelinux:8
      options: --privileged 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          dnf install -y rpm-build rpmdevtools python3
          rpmdev-setuptree

      - name: Prepare sources
        run: |
          cp src/pinvirt.py /root/rpmbuild/SOURCES/
          cp rpm/pinvirt.spec /root/rpmbuild/SPECS/

      - name: Build RPM
        run: |
          rpmbuild -ba /root/rpmbuild/SPECS/pinvirt.spec

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: pinvirt-rpms-ol8
          path: /root/rpmbuild/RPMS/noarch/
          if-no-files-found: error

  build-centos9:
    name: Build RPM on Rocky Linux 9
    runs-on: ubuntu-latest

    container:
      image: rockylinux:9.3.20231119-minimal
      options: --privileged 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          dnf install -y rpm-build rpmdevtools python3
          rpmdev-setuptree

      - name: Prepare sources
        run: |
          cp src/pinvirt.py /root/rpmbuild/SOURCES/
          cp rpm/pinvirt.spec /root/rpmbuild/SPECS/

      - name: Build RPM
        run: |
          rpmbuild -ba /root/rpmbuild/SPECS/pinvirt.spec

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: pinvirt-rpms-centos9
          path: /root/rpmbuild/RPMS/noarch/
          if-no-files-found: error
