name: Test and Build RPM

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  test:
    name: Run Python Unit Tests
    runs-on: ubuntu-latest

    container:
      image: oraclelinux:8
      options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Enable newer Python module and install
        run: |
          dnf -y module enable python311 
          dnf -y install python311 python311-pip
          python3.11 -m pip install --upgrade pip pytest

      - name: Install Python and Pytest
        run: |
          yum install -y python3 python3-pip
          pip3 install pytest
        
      - name: Prepare etc directory
        run: |
          mkdir -p /etc/pinvirt

      - name: Run tests
        run: |
          pytest src/test_pinvirt.py

  build-ol8:
    name: Build RPM on Oracle Linux 8
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')

    container:
      image: oraclelinux:8
      options: --privileged 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          yum install -y rpm-build rpmdevtools python3
          mkdir -p $HOME/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

      - name: Prepare sources
        run: |
          cp src/pinvirt.py $HOME/rpmbuild/SOURCES/
          cp rpm/pinvirt.spec $HOME/rpmbuild/SPECS/

      - name: Build RPM
        run: |
          rpmbuild -ba $HOME/rpmbuild/SPECS/pinvirt.spec

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: pinvirt-rpm-ol8
          path: /github/home/rpmbuild/RPMS/noarch/*.rpm 
          if-no-files-found: error

  build-rockylinux9:
    name: Build RPM on Rocky Linux 9
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')

    container:
      image: rockylinux:9.3
      options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          yum install -y rpm-build rpmdevtools python3
          mkdir -p $HOME/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

      - name: Prepare sources
        run: |
          cp src/pinvirt.py $HOME/rpmbuild/SOURCES/
          cp rpm/pinvirt.spec $HOME/rpmbuild/SPECS/

      - name: Build RPM
        run: |
          rpmbuild -ba $HOME/rpmbuild/SPECS/pinvirt.spec

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: pinvirt-rpm-el9
          path: /github/home/rpmbuild/RPMS/noarch/*.rpm 
          if-no-files-found: error
